DEBUG = False
TESTING = False
PORT = 5000
DIR_INPUT = "resources/1342-0.txt"
# DIR_INPUT = "resources/korean.txt"
DIR_OUTPUT = "typeahead_index"
# DIR_UPDATE = "update.txt"
VERSION = 0
HEAP_SIZE = 5
PREFIX_SIZE = 5
